server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /api

spring:
  application:
    name: gestao-b2b

  datasource:
    url:  ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    date-format: yyyy-MM-dd
    time-zone: America/Sao_Paulo

logging:
  level:
    root: INFO
    com.suaempresa: DEBUG