server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /api

spring:
  application:
    name: gestao-b2b

  datasource:
    url:  ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    date-format: yyyy-MM-dd
    time-zone: America/Sao_Paulo

logging:
  level:
    root: INFO
    com.suaempresa: DEBUG