CREATE TABLE clientes(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY ,
    nome_fantasia VARCHAR(120) NOT NULL,
    razao_social VARCHAR(60) NOT NULL,
    cnpj VARCHAR(14) NOT NULL,
    email VARCHAR(320),
    numero_celular VARCHAR(20),
    criado_em TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    atualizado_em TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    CONSTRAINT pk_clientes PRIMARY KEY (id),
    CONSTRAINT uk_clientes_cnpj UNIQUE (cnpj)
);
