CREATE TABLE clientes(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY ,
    nome_fantasia VARCHAR(120) NOT NULL,
    razao_social VARCHAR(60) NOT NULL,
    cnpj VARCHAR(14) NOT NULL,
    email VARCHAR(320),
    telefone VARCHAR(11),
    criado_em TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    atualizado_em TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    CONSTRAINT pk_clientes PRIMARY KEY (id),

    CONSTRAINT uk_clientes_cnpj UNIQUE (cnpj)

);
CREATE TABLE usuarios(
    id BIGINT GENERATED  BY DEFAULT AS IDENTITY ,
    nome_completo VARCHAR(300) NOT NULL,
    cpf VARCHAR(11) NOT NULL,
    matricula VARCHAR(8) NOT NULL,
    telefone VARCHAR(11),
    email VARCHAR(320),
    ativo BOOLEAN NOT NULL,
    papel VARCHAR(20) NOT NULL,
    criado_em TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    atualizado_em TIMESTAMP(6) WITH TIME ZONE NOT NULL,

   CONSTRAINT pk_usuarios PRIMARY KEY (id),

   CONSTRAINT uk_usuarios_cpf UNIQUE (cpf),
   CONSTRAINT uk_usuarios_matricula UNIQUE (matricula),
   CONSTRAINT uk_usuarios_email UNIQUE (email),

   CONSTRAINT ck_usuarios_papel CHECK (
    papel IN (
     'ADMIN',
     'VENDEDOR',
     'LOGISTICA',
     'FINANCEIRO'
             )
       )
);

CREATE TABLE produtos(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    sku VARCHAR(100) NOT NULL,
    codigo_fabricante VARCHAR(150),
    gtin VARCHAR(14) NOT NULL,
    nome VARCHAR(255) NOT NULL,
    descricao VARCHAR(255),
    marca VARCHAR(150),
    fabricante VARCHAR(200) NOT NULL,
    categoria VARCHAR(150) NOT NULL,
    ativo BOOLEAN NOT NULL,
    preco_base NUMERIC(19, 2) NOT NULL,
    criado_em TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    atualizado_em TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    CONSTRAINT pk_produtos PRIMARY KEY (id),

    CONSTRAINT uk_produtos_sku UNIQUE (sku),
    CONSTRAINT uk_produtos_gtin unique (gtin),

    CONSTRAINT ck_produtos_preco_base CHECK (preco_base>=0)
    );

CREATE TABLE enderecos(
     id BIGINT GENERATED BY DEFAULT AS IDENTITY,
     tipo VARCHAR(20) NOT NULL,
     cep VARCHAR(8) NOT NULL,
     logradouro VARCHAR(150) NOT NULL,
     numero VARCHAR(20),
     complemento VARCHAR(100),
     bairro VARCHAR(100) NOT NULL,
     cidade VARCHAR(100) NOT NULL,
     estado VARCHAR(2) NOT NULL,
     ativo BOOLEAN NOT NULL,
     cliente_id BIGINT NOT NULL,
     criado_em TIMESTAMP(6) WITH TIME ZONE NOT NULL,
     atualizado_em TIMESTAMP(6) WITH TIME ZONE NOT NULL,

     CONSTRAINT pk_enderecos PRIMARY KEY (id),

     CONSTRAINT fk_enderecos_clientes
        FOREIGN KEY (cliente_id) references clientes(id),

     CONSTRAINT ck_enderecos_tipos CHECK (
         tipo IN (
             'FISCAL',
             'COMERCIAL',
             'COBRANCA',
             'ENTREGA'
             )
         )
    );
CREATE INDEX idx_enderecos_cliente_id
      ON enderecos(cliente_id);

CREATE TABLE propostas(
     id BIGINT GENERATED BY DEFAULT AS IDENTITY,
     titulo VARCHAR(255) NOT NULL,
     descricao VARCHAR(2000),
     status_proposta VARCHAR(30) NOT NULL,
     valor_subtotal NUMERIC(19, 2) NOT NULL,
     valor_desconto NUMERIC(19, 2),
     observacao VARCHAR(500),
     ativo BOOLEAN NOT NULL,
     cliente_id BIGINT NOT NULL,
     usuario_id BIGINT NOT NULL,
     criado_em TIMESTAMP(6) WITH TIME ZONE NOT NULL,
     atualizado_em TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    CONSTRAINT pk_propostas PRIMARY KEY (id),

    CONSTRAINT fk_propostas_clientes
        FOREIGN KEY (cliente_id) REFERENCES clientes(id),

    CONSTRAINT fk_propostas_usuarios
        FOREIGN KEY (usuario_id) REFERENCES usuarios(id),

    CONSTRAINT ck_propostas_status CHECK (
        status_proposta IN (
            'RASCUNHO',
            'APROVACAO_PENDENTE',
            'APROVADA',
            'ENVIADA',
            'ACEITA',
            'RECUSADA',
            'CANCELADA',
            'CONVERTIDA'
            )
        ),

    CONSTRAINT ck_propostas_subtotal CHECK ( valor_subtotal>=0 ),
    CONSTRAINT ck_propostas_desconto CHECK (
        valor_desconto IS NULL
        OR  (valor_desconto >=0 AND valor_desconto <= valor_subtotal)
        )
);

CREATE INDEX idx_propostas_cliente_id
    ON propostas(cliente_id);
CREATE INDEX idx_propostas_usuario_id
    ON propostas(usuario_id);

CREATE TABLE itens_proposta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    valor_unitario NUMERIC(19, 2) NOT NULL,
    quantidade NUMERIC(19, 3) NOT NULL,
    valor_total NUMERIC(19, 2) NOT NULL,
    observacao VARCHAR(500),
    proposta_id BIGINT NOT NULL,
    produto_id BIGINT NOT NULL,
    criado_em TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    atualizado_em TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    CONSTRAINT pk_itens_proposta PRIMARY KEY (id),

    CONSTRAINT fk_itens_proposta_produtos
        FOREIGN KEY (produto_id) REFERENCES produtos(id),

    CONSTRAINT fk_itens_proposta_propostas
       FOREIGN KEY (proposta_id) REFERENCES propostas(id),

    CONSTRAINT ck_itens_proposta_valor_unitario
        CHECK (valor_unitario >=0),

    CONSTRAINT ck_itens_proposta_valor_total
        CHECK (valor_total>=0),

    CONSTRAINT ck_itens_proposta_quantidade
        CHECK (quantidade>0),

    CONSTRAINT ck_itens_proposta_valor_total_calculado
        CHECK ( valor_total = ROUND(valor_unitario*quantidade, 2) )
    );

CREATE INDEX idx_itens_proposta_produto_id
    ON itens_proposta(produto_id);

CREATE INDEX idx_itens_proposta_proposta_id
    ON itens_proposta(proposta_id);

CREATE TABLE aprovacoes_financeiras(
id BIGINT GENERATED BY DEFAULT AS IDENTITY,
proposta_id BIGINT NOT NULL,
usuario_id BIGINT NOT NULL,
resultado_aprovacao VARCHAR(30) NOT NULL,
observacao VARCHAR(2000),
criado_em TIMESTAMP(6) WITH TIME ZONE NOT NULL,
atualizado_em TIMESTAMP(6) WITH TIME ZONE NOT NULL,

CONSTRAINT pk_aprovacoes_financeiras PRIMARY KEY (id),

CONSTRAINT fk_aprovacoes_financeiras_propostas
    FOREIGN KEY (proposta_id) REFERENCES propostas(id),

CONSTRAINT fk_aprovacoes_financeiras_usuarios
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id),

CONSTRAINT ck_aprovacoes_financeiras_resultado CHECK (
    resultado_aprovacao IN (
              'APROVADO',
              'REPROVADO',
              'AJUSTES_SOLICITADOS'
        )
    ),
CONSTRAINT ck_aprovacoes_financeiras_observacao CHECK (
    resultado_aprovacao = 'APROVADO'
        OR (
        observacao IS NOT NULL
            AND BTRIM(observacao) <> ''
        )
    )

);

CREATE INDEX idx_aprovacoes_financeiras_proposta_id
    ON aprovacoes_financeiras(proposta_id);

CREATE INDEX idx_aprovacoes_financeiras_usuario_id
    ON aprovacoes_financeiras(usuario_id);